global:
  scrape_interval: 15s
  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres.railway.internal:5432']

  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis.railway.internal:6379']
  - job_name: 'gin_app'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['deploy-tool-device-management-dev.up.railway.app']
